---
title: "Abiotic data - Waterbath test"
author: "Chiara Duijser"
date: "2023-03-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries
```{r}
library(dplyr)
library(lubridate)
library(ggplot2)
library(RColorBrewer)
```

# Waterbath test
## Mangrove logger
```{r}
m_waterbath <- read.csv("../230329 Mangrove HOBO Waterbath test.csv", header=FALSE, comment.char="#", stringsAsFactors=TRUE)

# The time variable isn't at the date format, so time series data won't work. 
m_waterbath$Date_Time <- as.POSIXct(m_waterbath$Date_Time, format = "%m/%d/%Y %H:%M:%S") #- or /
str(m_waterbath)

# Set the range of datetimes (1 year)
m_start_wb <- as.POSIXct("2023-03-29 11:07:23", format = "%Y-%m-%d %H:%M:%S")
m_end_wb <- as.POSIXct("2023-03-29 16:16:23", format = "%Y-%m-%d %H:%M:%S")

# Subset the data within the datetime range
m_waterbath <- m_waterbath[m_waterbath$Date_Time >= m_start_wb & m_waterbath$Date_Time <= m_end_wb, ]
```


## Graph for mangrove logger
```{r}
ylab <- expression("Temperature " ( degree*C))
(m_temp_wb <- ggplot(m_waterbath, aes(x=Date_Time, y=Temperature)) +
  geom_line(color="#33A02C") + 
  labs(x="", y=ylab, title="Mangrove logger waterbath") +
  theme_bw())

ylab <- "pH"
(m_pH_wb <- ggplot(m_waterbath, aes(x=Date_Time, y=pH_T)) +
  geom_line(color="#33A02C") + 
  labs(x="", y=ylab) +
  theme_bw())
```

## Reef logger 
```{r}
r_waterbath <- read.csv("../230329 Reef HOBO Waterbath test.csv", header=FALSE, comment.char="#", stringsAsFactors=TRUE)

# The time variable isn't at the date format, so time series data won't work. 
r_waterbath$Date_Time <- as.POSIXct(r_waterbath$Date_Time, format = "%m/%d/%Y %H:%M:%S") #- or /
str(r_waterbath)

# Set the range of datetimes (1 year)
r_start_wb <- as.POSIXct("2023-03-29 11:07:04", format = "%Y-%m-%d %H:%M:%S")
r_end_wb <- as.POSIXct("2023-03-29 16:14:04", format = "%Y-%m-%d %H:%M:%S")

# Subset the data within the datetime range
r_waterbath <- r_waterbath[r_waterbath$Date_Time >= r_start_wb & r_waterbath$Date_Time <= r_end_wb, ]
```


## Graph for reef logger
```{r}
ylab <- expression("Temperature " ( degree*C))
(r_temp_wb <- ggplot(r_waterbath, aes(x=Date_Time, y=Temperature)) +
  geom_line(color="#1F78B4") + 
  labs(x="", y=ylab, title="Reef logger waterbath") +
  theme_bw())

ylab <- "pH"
(r_pH_wb <- ggplot(r_waterbath, aes(x=Date_Time, y=pH_T)) +
  geom_line(color="#1F78B4") + 
  labs(x="", y=ylab) +
  theme_bw())
```


# Mangrove and reef logger lines in one graph
```{r}
ylab <- expression("Temperature " ( degree*C))
(mr_temp_wb <- ggplot() +
  geom_line(data=m_waterbath, aes(x=Date_Time, y=Temperature), color = "#33A02C") +
  geom_line(data=r_waterbath, aes(x=Date_Time, y=Temperature), color = "#1F78B4") +
  labs(x="", y=ylab, title="Reef/Mangrove logger waterbath") +
  theme_bw())

ylab <- "pH"
(mr_pH_wb <- ggplot() +
  geom_line(data=m_waterbath, aes(x=Date_Time, y=pH_T), color = "#33A02C") +
  geom_line(data=r_waterbath, aes(x=Date_Time, y=pH_T), color = "#1F78B4") +
  labs(x="", y=ylab, title="Reef/Mangrove logger waterbath") +
  scale_y_continuous(breaks=c(8.0, 8.05, 8.1, 8.15, 8.2, 8.25, 8.3)) +
  theme_bw())

# Supplementary Figure 4
ggarrange(mr_temp_wb, mr_pH_wb,
          labels=c("A", "B"))
ggsave("M_R_Waterbath.pdf", width=7, height=4.5)
```


